# Generated by Django 4.1.1 on 2022-09-13 19:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('favorites', models.BooleanField(default=False)),
            ],
        ),
    ]
