# Generated by Django 4.1.1 on 2022-09-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='favorites',
            new_name='favorite',
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
