# Generated by Django 4.1.1 on 2022-09-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_favorites_note_favorite_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
