# Generated by Django 4.1.1 on 2022-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_due', models.DateField()),
                ('time_due', models.TimeField()),
            ],
        ),
    ]
