# Generated by Django 4.1.1 on 2022-09-15 13:04

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_name_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to='media/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
