# Generated by Django 4.1.1 on 2022-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_due',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
