# Generated by Django 4.1.1 on 2022-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_time_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_due',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
